authors:
  ayoub:
    name: Ayoub Bih
    description: ML Engineer | LLM Inference & Quantization
    avatar: https://github.com/identicons/ayoub.png
    url: https://linkedin.com/in/ayoub-bih/
  ayoub-quantization:
    name: Ayoub Bih
    description: ML Engineer | LLM Inference & Quantization
    avatar: https://github.com/identicons/ayoub-quantization.png
    url: https://linkedin.com/in/ayoub-bih/
  ayoub-awq:
    name: Ayoub Bih
    description: ML Engineer | LLM Inference & Quantization
    avatar: https://github.com/identicons/ayoub-awq.png
    url: https://linkedin.com/in/ayoub-bih/
